import { cp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { resolve } from "node:path";
import { buildBrandConfigFromProject } from "./projectBrand";
import { readProject } from "./projectStore";

export type ExportResult = {
  outputDir: string;
  files: string[];
};

export async function exportStaticSite(brandId = "irie-demo"): Promise<ExportResult> {
  const cwd = process.cwd();
  const project = await readProject();
  const brand = buildBrandConfigFromProject(project);
  const outputDir = resolve(cwd, "exports", `${brandId}-animated-site`);
  const framesDir = resolve(cwd, "public", "frames", brandId);
  const manifestPath = resolve(framesDir, "frames.manifest.json");

  if (!existsSync(framesDir)) {
    throw new Error(`Missing frames directory: ${framesDir}`);
  }

  await rm(outputDir, { recursive: true, force: true });
  await mkdir(resolve(outputDir, "public", "frames"), { recursive: true });
  await mkdir(resolve(outputDir, "brands"), { recursive: true });
  await mkdir(resolve(outputDir, "assets"), { recursive: true });
  await cp(framesDir, resolve(outputDir, "public", "frames", brandId), { recursive: true });
  await writeFile(resolve(outputDir, "brands", `${brandId}.json`), `${JSON.stringify(brand, null, 2)}\n`, "utf8");

  for (const asset of project.assets) {
    if (existsSync(asset.path)) {
      await cp(asset.path, resolve(outputDir, "assets", `${asset.id}-${asset.name.replace(/[^a-zA-Z0-9._-]/g, "-")}`));
    }
  }

  const manifest = JSON.parse(await readFile(manifestPath, "utf8"));
  const hero = manifest.scenes?.[0];

  await writeFile(
    resolve(outputDir, "index.html"),
    buildStaticHtml(brand, manifest, hero),
    "utf8"
  );
  await writeFile(
    resolve(outputDir, "README.md"),
    [
      `# ${brand.name} animated site export`,
      "",
      "This package was generated by Irie Animate.",
      "",
      "## View locally",
      "",
      "```bash",
      "python3 -m http.server 8080",
      "```",
      "",
      "Open http://localhost:8080.",
      "",
      "## Deploy",
      "",
      "Upload this folder to static hosting or run your Vercel deploy flow.",
      "",
      "## Source",
      "",
      `Project: ${project.name}`,
      `Scenes: ${project.scenes.length}`,
      `Assets: ${project.assets.length}`
    ].join("\n"),
    "utf8"
  );

  return {
    outputDir,
    files: ["index.html", "README.md", `brands/${brandId}.json`, `public/frames/${brandId}/frames.manifest.json`, ...project.assets.map((asset) => `assets/${asset.id}-${asset.name.replace(/[^a-zA-Z0-9._-]/g, "-")}`)]
  };
}

function buildStaticHtml(brand: any, manifest: any, hero: any) {
  const sceneJson = JSON.stringify(hero || {});
  const brandJson = JSON.stringify({ id: brand.id, name: brand.name, colors: brand.colors, logoText: brand.logoText, tagline: brand.tagline });
  const headline = escapeHtml(hero?.title || brand.name);
  const support = escapeHtml(brand.tagline || "Scroll to discover");
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${escapeHtml(brand.name)} Animated Site</title>
  <style>
    body { margin: 0; min-height: 220vh; background: #050505; color: #f4f0e8; font-family: Inter, system-ui, sans-serif; }
    .stage { position: sticky; top: 0; height: 100vh; overflow: hidden; background: #050505; }
    canvas { width: 100%; height: 100%; display: block; }
    .copy { position: fixed; left: 7vw; top: 36vh; max-width: 520px; pointer-events: none; }
    .copy h1 { margin: 0; font-family: Georgia, serif; font-size: clamp(48px, 7vw, 108px); line-height: .92; color: ${brand.colors.secondary}; font-weight: 400; letter-spacing: .12em; }
    .copy p { color: #d8d8d8; letter-spacing: .22em; text-transform: uppercase; }
    .mark { position: fixed; top: 28px; left: 32px; color: ${brand.colors.secondary}; letter-spacing: .16em; font-family: Georgia, serif; }
  </style>
</head>
<body>
  <section class="stage"><canvas id="scene"></canvas></section>
  <div class="mark">${escapeHtml(brand.logoText || brand.name)}</div>
  <div class="copy"><h1>${headline}</h1><p>${support}</p></div>
  <script>
    const scene = ${sceneJson};
    const brand = ${brandJson};
    const canvas = document.getElementById("scene");
    const ctx = canvas.getContext("2d");
    const frames = [];
    let loaded = 0;
    const count = scene.frameCount || 1;
    for (let i = 1; i <= count; i++) {
      const img = new Image();
      img.src = "/frames/${brand.id || "irie-demo"}/" + scene.id + "/desktop/frame-" + String(i).padStart(4, "0") + ".webp";
      img.onload = () => { loaded++; draw(); };
      frames.push(img);
    }
    function draw() {
      const dpr = Math.min(devicePixelRatio || 1, 2);
      canvas.width = innerWidth * dpr;
      canvas.height = innerHeight * dpr;
      const maxScroll = document.documentElement.scrollHeight - innerHeight;
      const progress = Math.max(0, Math.min(1, scrollY / maxScroll));
      const img = frames[Math.min(frames.length - 1, Math.round(progress * (frames.length - 1)))] || frames[0];
      ctx.fillStyle = "#050505";
      ctx.fillRect(0, 0, canvas.width, canvas.height);
      if (img && img.complete) {
        const scale = Math.max(canvas.width / img.naturalWidth, canvas.height / img.naturalHeight);
        const w = img.naturalWidth * scale;
        const h = img.naturalHeight * scale;
        ctx.drawImage(img, (canvas.width - w) / 2, (canvas.height - h) / 2, w, h);
      }
    }
    addEventListener("scroll", draw, { passive: true });
    addEventListener("resize", draw);
    draw();
  </script>
</body>
</html>`;
}

function escapeHtml(value: string) {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}
